# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=1.0.0
maven_group=dev.adamfr06
archives_base_name=TranslateEverything
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.154.2+26.2
modmenu_version=20.0.0
